In [91]:
import numpy as np
import pandas as pd
import random
import itertools as it

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [2]:
arr_ex = np.array(np.random.randint(10000, size=random.randint(1, 17)))
arr_ex

array([6851, 5423, 2901, 5181, 8896, 9382, 7287, 5475, 5762, 3644, 9453,
       2946, 8061, 1872])

In [3]:
arr_ex[arr_ex > np.mean(arr_ex)]

array([6851, 8896, 9382, 7287, 9453, 8061])

**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [4]:
arr_ex2 = np.array(np.random.randint(0, 11, size=20))
arr_ex2

array([ 8,  5,  8,  8,  9,  1,  0,  4,  9,  7,  3, 10,  8,  1,  2,  7,  2,
        8,  7,  4])

In [5]:
arr_ex2[arr_ex2 - np.min(arr_ex2) == 5].shape[0]

1

In [6]:
np.mean(arr_ex2[1::2][arr_ex2[0::2] % 2 == 0])

5.5

**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [7]:
a = np.array(np.random.randint(1, 11, size=(5, 5)))
a

array([[ 8,  9,  5,  8,  8],
       [ 6,  5,  3,  6, 10],
       [ 9, 10,  4,  6,  1],
       [ 8,  5,  4,  6,  1],
       [ 7,  2,  3,  5,  1]])

In [8]:
a = np.where(a == np.max(a), a **2, a)
a

array([[  8,   9,   5,   8,   8],
       [  6,   5,   3,   6, 100],
       [  9, 100,   4,   6,   1],
       [  8,   5,   4,   6,   1],
       [  7,   2,   3,   5,   1]])

In [9]:
a = np.where(a % 2 == 0, 0, a)
a

array([[0, 9, 5, 0, 0],
       [0, 5, 3, 0, 0],
       [9, 0, 0, 0, 1],
       [0, 5, 0, 0, 1],
       [7, 0, 3, 5, 1]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [10]:
b = np.array(np.random.randint(-5, 6, size=(5, 5)))
b

array([[-4, -3, -1, -2,  0],
       [ 0, -5, -1, -3,  1],
       [ 0,  2, -3,  4, -1],
       [ 2,  2,  5,  5,  4],
       [ 1,  3,  3, -1,  2]])

In [11]:
b = np.where(b < 0, np.where(b < 0)[0].shape[0], b)
b

array([[10, 10, 10, 10,  0],
       [ 0, 10, 10, 10,  1],
       [ 0,  2, 10,  4, 10],
       [ 2,  2,  5,  5,  4],
       [ 1,  3,  3, 10,  2]])

# Pandas

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

In [13]:
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [16]:
print(f'Максимальная цена билета: {df["fare"].max()}. Медианная цена билета: {df["fare"].median()}')

Максимальная цена билета: 512.3292. Медианная цена билета: 14.4542


In [19]:
print(f'Доля выживших: {round(df["survived"].value_counts(normalize=True)[1] * 100, 2)}')

Доля выживших: 38.2


In [20]:
df['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [32]:
df[['pclass', 'sex', 'name']].groupby(by=['sex', 'pclass']).nunique()

name
sex    pclass      
female 1        144
       2        106
       3        215
male   1        179
       2        171
       3        492

In [29]:
mal_fc = df.query('pclass == 1 and sex == "male"')['name'].nunique()
fem_tc = df.query('pclass == 3 and sex == "female"')['name'].nunique()

In [33]:
print(f'Мужчин в первом классе: {mal_fc}. Женщин в третьем классе: {fem_tc}')

Мужчин в первом классе: 179. Женщин в третьем классе: 215


**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

1. Разобьём столбец name, поскольку нам нужно имя, а там склеено (по разделителю ".", а затем по разделителю "("), уберём значения, которые могут в дальнейшем запутать

In [192]:
df['only_name'] = df['name'].str.split('.').apply(lambda x: x[-1])
df['only_name'] = df['only_name'].str.split('(').apply(lambda x: x[0])
df['only_name'] = df['only_name'].str.split(' ').apply(lambda x: x[1:])
df['only_name'] = df['only_name'].apply(lambda x: [i for i in x if '"' not in i])
df['only_name'] = df['only_name'].apply(lambda x: [i for i in x if len(i) > 2])
df['only_name']

0               [Elisabeth, Walton]
1                  [Hudson, Trevor]
2                  [Helen, Loraine]
3       [Hudson, Joshua, Creighton]
4                          [Hudson]
                   ...             
1304                       [Hileni]
1305                      [Thamine]
1306                  [Mapriededer]
1307                        [Ortin]
1308                          [Leo]
Name: only_name, Length: 1309, dtype: object

2. Создадим списки с полом, склеенным именем, в которых значения повторяются столько раз, сколько имён имеет человек

In [207]:
sex_list = []
for i in range(len(df['sex'])):
    for j in range(len(df['only_name'][i])):
        sex_list.append(df['sex'][i])

sex_list

['female',
 'female',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'male',
 'female',
 'female',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'female',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'female',
 'female',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male',
 'female',
 'male',
 'male',
 'male',
 'female',
 'female',
 'female',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'female',
 'female',
 'male',
 'male',
 'female',
 'female',

In [206]:
an_list = []
for i in range(len(df['name'])):
    for j in range(len(df['only_name'][i])):
        an_list.append(df['name'][i])

an_list

['Allen, Miss. Elisabeth Walton',
 'Allen, Miss. Elisabeth Walton',
 'Allison, Master. Hudson Trevor',
 'Allison, Master. Hudson Trevor',
 'Allison, Miss. Helen Loraine',
 'Allison, Miss. Helen Loraine',
 'Allison, Mr. Hudson Joshua Creighton',
 'Allison, Mr. Hudson Joshua Creighton',
 'Allison, Mr. Hudson Joshua Creighton',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Anderson, Mr. Harry',
 'Andrews, Miss. Kornelia Theodosia',
 'Andrews, Miss. Kornelia Theodosia',
 'Andrews, Mr. Thomas Jr',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Artagaveytia, Mr. Ramon',
 'Astor, Col. John Jacob',
 'Astor, Col. John Jacob',
 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
 'Aubart, Mme. Leontine Pauline',
 'Aubart, Mme. Leontine Pauline',
 'Barber, Miss. Ellen "Nellie"',
 'Barkworth, Mr. Algernon Henry Wilson',
 'Barkworth, Mr. Algernon Henry Wilson',
 'Barkworth, Mr. Alge

3. Создадим кортеж из пары пол-имя, в котором множественные имена разделены

In [196]:
name_list = list(zip(sex_list, [x for y in df['only_name'] for x in y]))
name_list

[('female', 'Elisabeth'),
 ('female', 'Walton'),
 ('male', 'Hudson'),
 ('male', 'Trevor'),
 ('female', 'Helen'),
 ('female', 'Loraine'),
 ('male', 'Hudson'),
 ('male', 'Joshua'),
 ('male', 'Creighton'),
 ('female', 'Hudson'),
 ('male', 'Harry'),
 ('female', 'Kornelia'),
 ('female', 'Theodosia'),
 ('male', 'Thomas'),
 ('female', 'Edward'),
 ('female', 'Dale'),
 ('male', 'Ramon'),
 ('male', 'John'),
 ('male', 'Jacob'),
 ('female', 'John'),
 ('female', 'Jacob'),
 ('female', 'Leontine'),
 ('female', 'Pauline'),
 ('female', 'Ellen'),
 ('male', 'Algernon'),
 ('male', 'Henry'),
 ('male', 'Wilson'),
 ('male', 'John'),
 ('male', 'Quigg'),
 ('male', 'Edmond'),
 ('female', 'James'),
 ('female', 'Albina'),
 ('male', 'Thomson'),
 ('male', 'Richard'),
 ('male', 'Leonard'),
 ('female', 'Richard'),
 ('female', 'Leonard'),
 ('male', 'Karl'),
 ('male', 'Howell'),
 ('female', 'Rosalie'),
 ('female', 'Ellen'),
 ('male', 'Jakob'),
 ('male', 'Dickinson'),
 ('female', 'Dickinson'),
 ('female', 'Amelia'),
 ('

4. Из имеющихся данных создадим временный датасет

In [208]:
temp_df = pd.DataFrame(name_list, columns=['sex', 'only_name'])
temp_df['name'] = pd.Series(an_list)
temp_df

sex    only_name                            name
0     female    Elisabeth   Allen, Miss. Elisabeth Walton
1     female       Walton   Allen, Miss. Elisabeth Walton
2       male       Hudson  Allison, Master. Hudson Trevor
3       male       Trevor  Allison, Master. Hudson Trevor
4     female        Helen    Allison, Miss. Helen Loraine
...      ...          ...                             ...
1992  female       Hileni            Zabour, Miss. Hileni
1993  female      Thamine           Zabour, Miss. Thamine
1994    male  Mapriededer       Zakarian, Mr. Mapriededer
1995    male        Ortin             Zakarian, Mr. Ortin
1996    male          Leo              Zimmerman, Mr. Leo

[1997 rows x 3 columns]

In [198]:
temp_df.value_counts(subset=['only_name', 'sex'])

only_name  sex   
William    male      66
John       male      57
Henry      male      37
Charles    male      32
James      male      30
                     ..
Grice      female     1
Guentcho   male       1
Guillaume  female     1
           male       1
Zillah     female     1
Name: count, Length: 954, dtype: int64

5. Мне показалось странным, что среди женщин лидирует имя William, я решил дополнительно проверить на ошибки

In [199]:
temp_df.query('sex == "female"')['only_name'].value_counts()

only_name
William       19
John          15
Mary          14
Elizabeth     13
Anna          11
              ..
Florentina     1
Asuncion       1
Vivian         1
Sebastiano     1
Thamine        1
Name: count, Length: 380, dtype: int64

In [215]:
temp_df.query('sex == "female" and only_name == "William"')

sex only_name                                               name
68    female   William    Bucknell, Mrs. William Robert (Emma Eliza Ward)
95    female   William          Carter, Mrs. William Ernest (Lucile Polk)
104   female   William  Cavendish, Mrs. Tyrell William (Julia Florence...
205   female   William  Frauenthal, Mrs. Henry William (Clara Heinshei...
229   female   William      Graham, Mrs. William Thompson (Edith Junkins)
344   female   William    Minahan, Mrs. William Edward (Lillian E Thorpe)
433   female   William          Silvey, Mrs. William Baird (Alice Munger)
461   female   William     Spencer, Mrs. William Augustus (Marie Eugenie)
549   female   William  Angle, Mrs. William A (Florence "Mary" Agnes H...
585   female   William  Brown, Mrs. Thomas William Solomon (Elizabeth ...
700   female   William                    Hamalainen, Mrs. William (Anna)
764   female   William              Lahtinen, Mrs. William (Anna Sylfven)
889   female   William       Shelley, Mrs. William (Imanita Parrish Hall)
915   female   William                   Trout, Mrs. William H (Jessie L)
921   female   William  Turpin, Mrs. William John Robert (Dorothy Ann ...
1170  female   William     Coutts, Mrs. William (Winnie "Minnie" Treanor)
1527  female   William    Lobb, Mrs. William Arthur (Cordelia K Stanlick)
1758  female   William               Rice, Mrs. William (Margaret Norton)
1857  female   William    Skoog, Mrs. William (Anna Bernhardina Karlsson)

Почему? Откуда столько женщин с именем William?

In [216]:
temp_df.groupby(by='sex')['only_name'].agg(pd.Series.mode)

sex
female    William
male      William
Name: only_name, dtype: object

**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [34]:
df.query('embarked == "C" and age > 50')['name'].nunique()

27

In [37]:
df.query('sex == "female" and (age < 20 or age > 50)')['name'].nunique()

135

In [39]:
df.query('age > 70')['name'].nunique()

6

**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [41]:
df[['sex', 'age']].groupby(by='sex').mean().apply(lambda x: round(x, 2))

age
sex          
female  28.69
male    30.59

In [238]:
df['AgeGroup'] = df.age.apply(lambda x: 1 if x < 30 else 2 if x >= 30 and x < 60 else 3)
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest                    only_name  \
0       NaN                     St Louis, MO          [Elisabeth, Walton]   
1       NaN  Montreal, PQ / Chesterville, ON             [Hudson, Trevor]   
2       NaN  Montreal, PQ / Chesterville, ON             [Helen, Loraine]   
3     135.0  Montreal, PQ / Chesterville, ON  [Hudson, Joshua, Creighton]   
4       NaN  Montreal, PQ / Chesterville, ON                     [Hudson]   
...     ...                              ...                          ...   
1304  328.0                              NaN                     [Hileni]   
1305    NaN                              NaN                    [Thamine]   
1306  304.0                              NaN                [Mapriededer]   
1307    NaN                              NaN                      [Ortin]   
1308    NaN                              NaN                        [Leo]   

      AgeGroup  
0            1  
1            1  
2            1  
3            2  
4            1  
...        ...  
1304         1  
1305         3  
1306         1  
1307         1  
1308         1  

[1309 rows x 16 columns]

In [239]:
df.AgeGroup.value_counts()

AgeGroup
1    569
2    437
3    303
Name: count, dtype: int64

In [242]:
round(df[['survived', 'AgeGroup']].value_counts('AgeGroup', normalize=True) * 100, 2)

AgeGroup
1    43.47
2    33.38
3    23.15
Name: proportion, dtype: float64

In [42]:
df[['pclass', 'fare']].groupby(by='pclass').max()

fare
pclass          
1       512.3292
2        73.5000
3        69.5500

**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.